# render.yaml
services:
  - type: web
    name: feulfit-app
    env: ruby
    plan: free
    region: oregon  # change if needed
    branch: main
    buildCommand: bundle install && rails db:migrate && rails assets:precompile
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: feulfit-db   # Render Postgres DB you created
          property: connectionString
      - key: RAILS_MASTER_KEY
        value: "<your_rails_master_key_here>"
      - key: SECRET_KEY_BASE
        value: "<your_secret_key_base_here>"
    autoDeploy: true
